### ISSUE TITLE
question more than an issue.

### ISSUE THREAD

**Issue by malcorath** [Nubbin72/MULTIPLAYER#1]
What is the licence on these files ?

I am looking into learning some practical network coding to use for future projects and this looks like an exelent starter. 

Is it OK to DL and use and abuse ?

**Comment by Nubbin72** [comment]
Yes, you can use it as you wish.

**Comment by malcorath** [comment]
Sweet!  might I inquire if it is server authoritative? I see a lot of the code lies on the client-side.

**Comment by Nubbin72** [comment]
Yes, the server is authoritative. 
On client side there is some code for client-side prediction and interpolation.
Also, the I started adding some additional features to the game like chat, and scoreboard, so it's a bit more than just a basic networking example.
Right now I'm using TCP so the response can get a bit slow if too many players are connected. 

I had a plan for the last 3 years to refactor the game and switch to UDP, but tbh I completely  forgot about this project. I will look more into it in the next week or so and strip down some unnecessary features, switch to using UDP, and rewrite those ugly parts.

PS.
Thank you for showing interest in my project :)
